name: Download Artifacts
on:
  workflow_call:
    secrets: 
      DEV_SYNAPSE_WORKSPACE_NAME:
        required: true
        description: "Specifies the DEV_SYNAPSE_WORKSPACE_NAME."

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v2.1.1
        with:
          name: ${{ secrets.DEV_SYNAPSE_WORKSPACE_NAME }}
          path: ${{ needs.upload.outputs.artifact-path }}
