name: Synapse Publish Artifacts

on:
  workflow_call:
    secrets: 
      CLIENT_ID:
        required: true
        description: "Specifies the client ID."
      AZURE_SUBSCRIPTION_ID:
        required: true
        description: "Specifies the subscription id of the deployment."
      TENANT_ID:
        required: true
        description: "Specifies the tenant id of the deployment."
      CLIENT_SECRET:
        required: true
        description: "Specifies the azure credentials for deployment."
      DEV_AZURE_RESOURCE_GROUP_NAME:
        required: true
        description: "Specifies the dev synapse workspace name for deployment."
      DEV_SYNAPSE_WORKSPACE_NAME:
        required: true
        description: "Specifies the dev synapse workspace name for deployment."

jobs:
  Publish_Artifacts:
    name: Publish_Artifacts
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: dev

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2

      # Validate Synapse Artifacts
      - name: Publish Artifacts
        id: validation_synapse
        uses: azure/synapse-workspace-deployment@V1.7.0
        with:
          TargetWorkspaceName: ${{ secrets.DEV_SYNAPSE_WORKSPACE_NAME }}
          ArtifactsFolder: ${{ github.workspace }}/code/synapse
          resourceGroup: ${{ secrets.DEV_AZURE_RESOURCE_GROUP_NAME }}
          operation: "validate"
          deployManagedPrivateEndpoint: true
          DeleteArtifactsNotInTemplate: false

      - name: Upload Synapse template as artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
           name: ${{ secrets.DEV_SYNAPSE_WORKSPACE_NAME }}
           path: /home/runner/work/udf-synapse/udf-synapse/ExportedArtifacts