name: Synapse Artifacts Publish

on:
  push:
    branches: [main]
    paths:
    - 'code/**'

jobs:
  Publish_Artifacts:
    name: Publish_Artifacts
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    runs-on: self-hosted
    continue-on-error: false
    environment: dev

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      # Validate Synapse Artifacts
      - name: Publish Artifacts
        id: validation_synapse
        uses: azure/synapse-workspace-deployment@V1.7.0
        with:
          TargetWorkspaceName: ${{ secrets.DEV_SYNAPSE_WORKSPACE_NAME }}
          ArtifactsFolder: ${{ github.workspace }}/code/synapse
          resourceGroup: ${{ secrets.DEV_AZURE_RESOURCE_GROUP_NAME }}
          operation: "validate"
          deployManagedPrivateEndpoint: true
          DeleteArtifactsNotInTemplate: false

      - name: Upload Synapse template as artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
           name: ${{ secrets.DEV_SYNAPSE_WORKSPACE_NAME }}
           path: /home/azureadmin/actions-runner/_work/udf-synapse/udf-synapse/ExportedArtifacts
      
      - name: Assign user
        env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"assignees": ["Himanshu8445"]}' 
            https://api.github.com/repos/udf-synapse/issues/${PR_NUMBER}/assignees

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          branch: publish
          commit_options: '--no-verify --signoff'
          commit_author: Himanshu8445
          status_options: '--untracked-files=no'
          skip_dirty_check: true