name: Synapse Artifacts Publish

on:
  push:
    branches: [main]
    paths:
    - 'code/synapse'

jobs:
  Publish_Artifacts:
    name: Publish_Artifacts
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: dev

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2

      # Validate Synapse Artifacts
      - name: Publish Artifacts
        id: validation_synapse
        uses: azure/synapse-workspace-deployment@V1.7.0
        with:
          TargetWorkspaceName: ${{ secrets.DEV_SYNAPSE_WORKSPACE_NAME }}
          ArtifactsFolder: ${{ github.workspace }}/code/synapse
          resourceGroup: ${{ secrets.DEV_AZURE_RESOURCE_GROUP_NAME }}
          operation: "validate"
          deployManagedPrivateEndpoint: true
          DeleteArtifactsNotInTemplate: false

      - name: Upload Synapse template as artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
           name: ${{ secrets.DEV_SYNAPSE_WORKSPACE_NAME }}
           path: /home/runner/work/udf-synapse/udf-synapse/ExportedArtifacts