name: Synapse Validation Template

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
      source_synapse_workspace_name:
        required: true
        type: string
        description: "Specifies the name of the synapse workspace."
      azure_resource_group_name:
        required: true
        description: "Specifies the name of the resource group for the deployment."
    secrets:
      AZURE_SUBSCRIPTION_ID:
        required: true
        description: "Specifies the subscription id of the deployment."
      TENANT_ID:
        required: true
        description: "Specifies the tenant id of the deployment."
      CLIENT_ID:
        required: true
        description: "Specifies the client id."
      CLIENT_SECRET:
        required: true
        description: "Specifies the client secret."

jobs:
  deployment:
    name: Validation for ${{ inputs.environment }}
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: ${{ inputs.environment }}

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2

      # Validate Synapse Artifacts
      - name: Validate Synapse Artifacts
        id: validation_synapse
        uses: azure/synapse-workspace-deployment@V1.7.0
        with:
          TargetWorkspaceName: ${{ inputs.source_synapse_workspace_name }}
          ArtifactsFolder: ${{ github.workspace }}/code/synapse
          operation: "validate"
          deployManagedPrivateEndpoint: true
          DeleteArtifactsNotInTemplate: false