name: Synapse Artifacts Deployment Test

on:
  workflow_call:
    secrets: 
      CLIENT_ID:
        required: true
        description: "Specifies the client ID."
      AZURE_SUBSCRIPTION_ID:
        required: true
        description: "Specifies the subscription id of the deployment."
      TENANT_ID:
        required: true
        description: "Specifies the tenant id of the deployment."
      CLIENT_SECRET:
        required: true
        description: "Specifies the azure credentials for deployment."
      TEST_SYNAPSE_WORKSPACE_NAME:
        required: true
        description: "Specifies the test synapse workspace name for deployment."
      TEST_AZURE_RESOURCE_GROUP_NAME:
        required: true
        description: "Specifies the test synapse workspace name for deployment."
      DEV_SYNAPSE_WORKSPACE_NAME:
        required: true
        description: "Specifies the dev synapse workspace name for deployment."

jobs:
  deployment:
    name: Deployment to test
    runs-on: self-hosted
    continue-on-error: false
    environment: test

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3
      
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          #enable-AzPSSession: true
      
      # - name: "Get working Az Context with PowerShell action"
      #   uses: azure/powershell@v1
      #   with:
      #     inlineScript: |
      #       Set-AzContext "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      #     azPSVersion: "latest"
      
      # # Install Required Modules
      # - name: Install Required Modules
      #   id: install_modules
      #   run: |
      #     Set-PSRepository PSGallery -InstallationPolicy Trusted
      #     Install-Module Az -ErrorAction Stop
      #   shell: pwsh
      #   working-directory: ${{ github.workspace }}/code/Scripts

        # Synapse Pre-Processing Step
      # - name: Synapse Pre-Processing Step
      #   id: synapse_preprocessing
      #   run: |
      #     ./SynapseRolloutPreprocessing.ps1 `
      #       -SubscriptionId "${{ secrets.AZURE_SUBSCRIPTION_ID }}" `
      #       -SynapseWorkspaceName "${{ secrets.TEST_SYNAPSE_WORKSPACE_NAME }}" `
      #       -CheckPastDaysOfPipelineRuns 1
      #   shell: pwsh
      #   working-directory: ${{ github.workspace }}/code/Scripts

      # Deploy Synapse Artifacts
      - name: Deploy Synapse Artifacts
        id: deployment_synapse
        uses: azure/synapse-workspace-deployment@V1.7.0
        with:
          TargetWorkspaceName: ${{ secrets.TEST_SYNAPSE_WORKSPACE_NAME }}
          TemplateFile: "https://github.com/Himanshu8445/udf-synapse/blob/publish/TemplateForWorkspace.json"
          ParametersFile: ${{ github.workspace }}/code/synapseParameters/param.test.json
          # ArtifactsFolder:
          operation: "deploy"
          deployManagedPrivateEndpoint: true
          # OverrideArmParameters:
          DeleteArtifactsNotInTemplate: false
          Environment: "Azure Public"
          resourceGroup: ${{ secrets.TEST_AZURE_RESOURCE_GROUP_NAME }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenantId: ${{ secrets.TENANT_ID }}          
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          managedIdentity: false

      # Synapse Post-Processing Step
      - name: Synapse Post-Processing Step
        id: synapse_postprocessing
        run: |
          ./SynapseRolloutPostprocessing.ps1 `
            -SubscriptionId "${{ secrets.AZURE_SUBSCRIPTION_ID }}" `
            -SynapseWorkspaceName "${{ secrets.TEST_SYNAPSE_WORKSPACE_NAME }}" `
            -TriggerNames "${{ steps.synapse_preprocessing.outputs.triggerNames }}"
        shell: pwsh
        working-directory: ${{ github.workspace }}/code/Scripts

      # Log out from Azure
      - name: 'Log out from Azure'
        run: |
          az logout